Updated requirements.txt
Version bump to Flask to fix "ImportError: cannot import name 'json' from 'itsdangerous'" error
Added Jinja version explicitly to fix "ImportError: cannot import name 'escape' from 'jinja2'" error